### ISSUE TITLE
Contact page UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Christopher-Zorc-Store-Dev#5]
Bug - Send button on contact page not visible on center.
Exp - Send button should be visible on center below text field.
Ref Link - https://nimb.ws/eobrIp

**Comment by stores-cedcommerce** [comment]
Bug - Send button on contact page not visible on center.
@ankitcedcoss  this is not a bug this button is disabled till form is not fill.

Exp - Send button should be visible on center below text field.
and this but can not stay in left because as per user experience uer submitting behaviour is right thats why I float to right.

**Comment by ankitcedcoss** [comment]
Closed on Not Required
